# Generated by Django 3.1.12 on 2022-12-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diabetes_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('blood_pressure', models.CharField(max_length=255)),
                ('glucose', models.CharField(max_length=255)),
                ('insulin', models.CharField(max_length=255)),
                ('insulin_name', models.CharField(max_length=255)),
                ('skin_thickness', models.CharField(max_length=255)),
            ],
        ),
    ]
