# Generated by Django 3.2.4 on 2022-12-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diabetes_table',
            name='insulin_name',
        ),
        migrations.AddField(
            model_name='diabetes_table',
            name='bmi',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='diabetes_table',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diabetes_table',
            name='blood_pressure',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='diabetes_table',
            name='glucose',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='diabetes_table',
            name='insulin',
            field=models.IntegerField(max_length=255),
        ),
    ]
