# Generated by Django 3.2.4 on 2022-12-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes_app', '0002_auto_20221209_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='diabetes_table',
            name='result',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diabetes_table',
            name='blood_pressure',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='diabetes_table',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diabetes_table',
            name='glucose',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='diabetes_table',
            name='insulin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diabetes_table',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diabetes_table',
            name='skin_thickness',
            field=models.FloatField(default=0.0),
        ),
    ]
